server:
  port: 80
  # servlet
  servlet:
    context-path: /

# spring
spring:
  application:
    name: shiroThemleaf
  # thymeleaf
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  # mysql
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.131.130:3306/shiro?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    # druid
    type: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceWrapper

  # redis
  redis:
    host: 192.168.131.130
    port: 6379
    password: root
    database: 0
    # jedis
    client-type: jedis
    jedis:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0

# mybatis-plus
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 一级缓存配置 一级缓存是本地或者说局部缓存，它不能被关闭，只能配置缓存范围。SESSION 或者 STATEMENT。
    local-cache-scope: session
    # 二级缓存总开关
    cache-enabled: true
  type-aliases-package: com.pepsiwyl.pojo
  mapper-locations: classpath*:/mapper/**/*.xml
